In [1]:
import pandas as pd
import numpy as np

viagra_spam = {'viagra':[1,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1],
               'spam':[1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,1,1]}
np_data = pd.DataFrame(viagra_spam).values
np_data[:5] #넘파이 배열

array([[1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 1],
       [1, 1]], dtype=int64)

In [2]:
#P(viagra)
p_v = sum(np_data[:, 0] == 1) / len(np_data)

#P(spam)
p_s = sum(np_data[:, 1] == 1) / len(np_data)

#P(viagra&spam)
p_vs = sum((np_data[:, 0] == 1) & (np_data[:, 1] == 1)) / len(np_data)

#P(~viagra&spam)
p_n_vs = sum((np_data[:, 0] == 0) & (np_data[:, 1] == 1)) / len(np_data)

p_v, p_s, p_vs, p_n_vs

(0.3, 0.3, 0.15, 0.15)

In [3]:
p_s * (p_vs / p_s ) / p_v

0.5

In [4]:
p_s * (p_vs /p_s ) / (1-p_v)

0.2142857142857143

In [5]:
import pandas as pd
import numpy as np

data_url = "https://raw.githubusercontent.com/prof-dana/Lecture-Code/refs/heads/main/MachineLearning/data/fraud.csv"
df= pd.read_csv(data_url) 
df.head()

   ID  History CoApplicant Accommodation  Fraud
0   1  current        none           own   True
1   2     paid        none           own  False
2   3     paid        none           own  False
3   4     paid   guarantor          rent   True
4   5  arrears        none           own  False

In [6]:
df.drop(columns=["ID"],inplace=True)
Y_data = df.pop("Fraud") #Fraud열은 빼서 Y_data에 저장
Y_data = Y_data.values #넘파이 array로 바꿈(열 이름X)
x_df = pd.get_dummies(df)
x_df.head(5).T

,0,1,2,3,4,5,6,7,8,9
History_arrears,False,False,False,False,True,True,False,True,False,False
History_current,True,False,False,False,False,False,True,False,True,False
History_none,False,False,False,False,False,False,False,False,False,True
History_paid,False,True,True,True,False,False,False,False,False,False
CoApplicant_coapplicant,False,False,False,False,False,False,False,False,False,False
CoApplicant_guarantor,False,False,False,True,False,False,False,False,False,False
CoApplicant_none,True,True,True,False,True,True,True,True,True,True
Accommodation_free,False,False,False,False,False,False,False,False,False,False
Accommodation_own,True,True,True,False,True,True,True,True,False,True
Accommodation_rent,False,False,False,True,False,False,False,False,True,False

In [7]:
x_data = x_df.values #넘파이 array로 바꿈
x_data[:5]

array([[False,  True, False, False, False, False,  True, False,  True,
        False],
       [False, False, False,  True, False, False,  True, False,  True,
        False],
       [False, False, False,  True, False, False,  True, False,  True,
        False],
       [False, False, False,  True, False,  True, False, False, False,
         True],
       [ True, False, False, False, False, False,  True, False,  True,
        False]])

In [8]:
from sklearn.naive_bayes import BernoulliNB

model = BernoulliNB()
model.fit(x_data, Y_data)

BernoulliNB()

In [9]:
y_prob = model.predict_proba(x_data)

print(y_prob)

[[0.71084848 0.28915152]
 [0.88059963 0.11940037]
 [0.88059963 0.11940037]
 [0.17911719 0.82088281]
 [0.92657726 0.07342274]
 [0.92657726 0.07342274]
 [0.71084848 0.28915152]
 [0.92657726 0.07342274]
 [0.34439038 0.65560962]
 [0.51962189 0.48037811]
 [0.73328558 0.26671442]
 [0.71084848 0.28915152]
 [0.34439038 0.65560962]
 [0.88059963 0.11940037]
 [0.92657726 0.07342274]
 [0.71084848 0.28915152]
 [0.75097402 0.24902598]
 [0.87517127 0.12482873]
 [0.92657726 0.07342274]
 [0.88059963 0.11940037]]

In [10]:
y_pred = model.predict(x_data)

print(y_pred)

[False False False  True False False False False  True False False False
  True False False False False False False False]

In [11]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_data, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.75

In [12]:
text_example = [ "A great game game",
    "The team played a great game",
    "The match was exciting",
    "A clean game with great players",
    "The team won the match",
    "The player scored a goal",
    "It was a close game",
    "The championship match was amazing",
    "The team celebrated the victory",
    "A fantastic game by the players",
    "The election results were announced",
    "The election campaign was intense",
    "The president won the election",
    "The government announced new policy",
    "The parliament passed the law",
    "The political debate was heated",
    "The candidate started the campaign",
    "The voters supported the candidate",
    "The election vote counting began",
    "The government election strategy changed"]

y = ["sports","sports","sports","sports","sports",
    "sports","sports","sports","sports","sports",
    "politics","politics","politics","politics","politics",
    "politics","politics","politics","politics","politics"]

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(text_example)

print(vectorizer.get_feature_names_out())#열 이름
print(X.toarray()[:5])

['amazing' 'announced' 'began' 'by' 'campaign' 'candidate' 'celebrated'
 'championship' 'changed' 'clean' 'close' 'counting' 'debate' 'election'
 'exciting' 'fantastic' 'game' 'goal' 'government' 'great' 'heated'
 'intense' 'it' 'law' 'match' 'new' 'parliament' 'passed' 'played'
 'player' 'players' 'policy' 'political' 'president' 'results' 'scored'
 'started' 'strategy' 'supported' 'team' 'the' 'victory' 'vote' 'voters'
 'was' 'were' 'with' 'won']
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 2 0 0 0 0 0 0 1]]

In [14]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X, y)

MultinomialNB()

In [15]:
test = ["the player wins"] # "the government election policy"
X_test = vectorizer.transform(test)#변환

print(model.predict_proba(X_test))
print(model.classes_)#라벨 이름
print(model.predict(X_test))

[[0.40313534 0.59686466]]
['politics' 'sports']
['sports']

In [16]:
from sklearn import datasets #내장 데이터셋 사용
from sklearn.naive_bayes import GaussianNB
import pandas as pd

iris = datasets.load_iris() #샘플 데이터 load
df_X=pd.DataFrame(iris.data) # feature
df_Y=pd.DataFrame(iris.target) #label(0,1,2로 표현)
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_X, df_Y, test_size=0.25)
X_train.shape, X_test.shape

((112, 4), (38, 4))

In [18]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X_train, y_train)

C:\Users\DANA-LAB\.conda\envs\ml\lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [19]:
#꽃받침 길이 5.1cm, 꽃받침 너비 3.5cm, 꽃잎 길이 1.4cm, 꽃잎 너비 0.2cm
test = [[5.1,3.5,1.4,0.2]]
idx = clf.predict(test)[0]
print(iris.target_names[idx])

setosa

In [20]:
from sklearn.metrics import confusion_matrix

y_pred = clf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[12,  0,  0],
       [ 0, 16,  2],
       [ 0,  2,  6]], dtype=int64)

In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.89      0.89      0.89        18
           2       0.75      0.75      0.75         8

    accuracy                           0.89        38
   macro avg       0.88      0.88      0.88        38
weighted avg       0.89      0.89      0.89        38